export const GAME_STATES = {
  LANDING: 'LANDING',
  CHARACTER_SELECTION: 'CHARACTER_SELECTION',
  DIALOGUE: 'DIALOGUE',
  MISSION: 'MISSION',
  CHALLENGE: 'CHALLENGE',
  REWARD: 'REWARD',
  TOWN_HUB: 'TOWN_HUB',
  VOYAGE: 'VOYAGE',
  ISLAND_FLOW: 'ISLAND_FLOW',
  WORLD_REVEAL: 'WORLD_REVEAL',
  SEA: 'SEA',
  ENDING: 'ENDING',
};