export const GAME_STATES = {
  LANDING: 'LANDING',
  CHARACTER_SELECTION: 'CHARACTER_SELECTION',
  DIALOGUE: 'DIALOGUE',
  MISSION: 'MISSION',
  CHALLENGE: 'CHALLENGE',
  REWARD: 'REWARD',
  TOWN_HUB: 'TOWN_HUB',
  VOYAGE: 'VOYAGE',
};