"""add cms fields to challenge

Revision ID: 3aaad49353af
Revises: a074896b2acd
Create Date: 2026-07-10 21:51:27.442735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaad49353af'
down_revision: Union[str, Sequence[str], None] = 'a074896b2acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('hint_2', sa.Text(), nullable=True))
    op.add_column('challenges', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('challenges', sa.Column('order_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'order_index')
    op.drop_column('challenges', 'is_active')
    op.drop_column('challenges', 'hint_2')
    # ### end Alembic commands ###
