"""Add CMS models for Phase 5A

Revision ID: a074896b2acd
Revises: bc0128af0489
Create Date: 2026-07-10 16:07:42.915953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a074896b2acd'
down_revision: Union[str, Sequence[str], None] = 'bc0128af0489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('islands',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('unlock_requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('content_version', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_islands_id'), 'islands', ['id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('island_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('sql_concept', sa.String(), nullable=True),
    sa.Column('expected_sql', sa.Text(), nullable=True),
    sa.Column('validation_type', sa.String(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('database_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('seed_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('npc', sa.String(), nullable=True),
    sa.Column('dialogue_ref', sa.String(), nullable=True),
    sa.Column('boss_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['island_id'], ['islands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('dialogues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('npc_id', sa.String(), nullable=False),
    sa.Column('dialogue_text', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('branches', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('conditions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('story_events', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('diamonds', sa.Integer(), nullable=True),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('achievement', sa.String(), nullable=True),
    sa.Column('key_codex_fragment', sa.String(), nullable=True),
    sa.Column('unlock_ship_ability', sa.String(), nullable=True),
    sa.Column('unlock_cosmetic', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('rewards')
    op.drop_table('dialogues')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_table('media')
    op.drop_index(op.f('ix_islands_id'), table_name='islands')
    op.drop_table('islands')
    # ### end Alembic commands ###
